version: "3.8"
services:
    # API
    app:
        build: ./
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $PORT:$PORT
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db

    # Database
    db:
        image: postgres
        restart: always
        env_file: ./.env
        container_name: nitprofile_database
        ports:
            - "5434:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: root
            POSTGRES_PASSWORD: rootpassword
            POSTGRES_DB: nitprofile_db

    # Adminer
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
    redis:
        image: redis:latest
        restart: always
        ports:
        - "6379:6379"
        volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        environment:
        - REDIS_PASSWORD=my-password
        - REDIS_PORT=6379
        - REDIS_DATABASES=16

volumes:
    pgdata:
        driver: local
